robot_description: package://robowflex_dataset/configs/robots/fetch.yaml
scene: package://robowflex_dataset/configs/scenes/shelf/scene_short.yaml
sensors: package://experience_experiments/datasets/IROS2021/configs/sensors_small.yaml
ompl_config: package://experience_experiments/datasets/IROS2021/configs/ompl_planning.yaml
queries: package://experience_experiments/datasets/IROS2021/configs/queries_small_pick.yaml
variation: package://experience_experiments/datasets/IROS2021/configs/variation_small.yaml
planning_group: arm_with_torso
samples: 200
